require_relative '../config/environment'
require 'faker'

# jemy = Person.create(name: 'Jemy', hunger: 8, tryptophan: 10, politics: 'blue')
Person.create(name: Faker::Name.name, hunger: 10, tryptophan: 10, politics: "Red")
Person.create(name: Faker::Name.name, hunger: 10, tryptophan: 10, politics: "Blue")
Person.create(name: Faker::Name.name, hunger: 10, tryptophan: 10, politics: "Blue")
Person.create(name: Faker::Name.name, hunger: 10, tryptophan: 10, politics: "Red")
Person.create(name: Faker::Name.name, hunger: 10, tryptophan: 10, politics: "Red")
Person.create(name: Faker::Name.name, hunger: 10, tryptophan: 10, politics: "Blue")

Thanksgiving.create!(course: "Turkey", strife: 0, location: "Daryl's Place")
Thanksgiving.create!(course: "Tofurky", strife: 0, location: "Ken's Place")
Thanksgiving.create!(course: "Turkey", strife: 0, location: "Mom's Place")
Thanksgiving.create!(course: "Tofurky", strife: 0, location: "Grandma's Place")
Thanksgiving.create!(course: "Tofurky", strife: 0, location: "Mavi's Place")
Thanksgiving.create!(course: "Turkey", strife: 0, location: "Firuz's Place")
Thanksgiving.create!(course: "Turkey", strife: 0, location: "Popeyes")
Thanksgiving.create!(course: "Turkey", strife: 0, location: "Mother-in-Law's")
Thanksgiving.create!(course: "Turkey", strife: 0, location: "Neighbor's")
Thanksgiving.create!(course: "Turkey", strife: 0, location: "Some Place In The Bronx")
Thanksgiving.create!(course: "Tofurky", strife: 0, location: "Graham's Place")
Thanksgiving.create!(course: "Turkey", strife: 0, location: "Kentucky Fried Chicken")
Thanksgiving.create!(course: "Turkey", strife: 0, location: "Boston Market")
Thanksgiving.create!(course: "Tofurky", strife: 0, location: "Your Boss's place")
Thanksgiving.create!(course: "Tofurky", strife: 0, location: "Soup Kitchen")
Thanksgiving.create!(course: "Tofurky", strife: 0, location: "Nicky's Place")
Thanksgiving.create!(course: "Turkey", strife: 0, location: "Friendsgiving, but more like acquaintances")
Thanksgiving.create!(course: "Turkey", strife: 0, location: "Aunt's Place")
Thanksgiving.create!(course: "Turkey", strife: 0, location: "Friendsgiving")

# Thanksgiving.create!(course: "Turkey", strife: 0, location: "Stay Home")
